## Creating an array

In [1]:
import numpy as np 

In [2]:
a = [ n for n in range(1,11)]

In [3]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
na = np.arange(1,11)

In [11]:
na

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Performance difference 

In [13]:
%timeit [ n * n for n in a]

1.05 µs ± 58.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
%timeit na * na  

774 ns ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
na = np.array([10,20,30])

In [16]:
na

array([10, 20, 30])

In [17]:
type(na)

numpy.ndarray

In [18]:
chs = np.array("Python")

In [19]:
chs

array('Python', dtype='<U6')

In [20]:
zeros = np.zeros(10)

In [21]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
ones = np.ones(10)

In [25]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
d2 = np.full( (3,3), 10)

In [24]:
d2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [39]:
d2.shape

(3, 3)

In [31]:
ea = np.empty(5)

In [32]:
ea

array([8.48798316e-314, 3.39519327e-313, 7.63918485e-313, 1.35807731e-312,
       2.12199579e-312])

In [36]:
a = np.arange(1,11, dtype=np.int16)

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
a.dtype

dtype('int16')

In [38]:
a.shape

(10,)

In [40]:
a.size

10

In [41]:
d2.size

9

In [42]:
d2.dtype

dtype('int32')

In [43]:
d2.ndim

2

In [44]:
a.ndim

1

## Random nums generation

In [46]:
ra = np.random.randint(10,20,10)

In [47]:
ra

array([10, 11, 19, 18, 17, 13, 10, 10, 16, 16])

In [55]:
aa,sv =  np.linspace(1,10,20, retstep=True)

In [56]:
aa

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [57]:
sv

0.47368421052631576

## Indexing

In [59]:
a = np.arange(1,11)

In [60]:
a[1]

2

In [61]:
a[5:]

array([ 6,  7,  8,  9, 10])

In [62]:
a[-1]

10

In [63]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [64]:
a[-5:8]

array([6, 7, 8])

In [66]:
td = np.arange(1,10).reshape((3,3))

In [67]:
td

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
td[1,1]

5

In [70]:
td[1,-1]

6

In [74]:
td[1]   

array([4, 5, 6])

In [75]:
td[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
td[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [78]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
a.sum()

55