## Creating an array

In [2]:
import numpy as np 

In [3]:
a = [ n for n in range(1,11)]

In [4]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
na = np.arange(1,11)

In [6]:
na

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Performance difference 

In [7]:
%timeit [ n * n for n in a]

1.17 µs ± 164 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
%timeit na * na  

743 ns ± 31.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
na = np.array([10,20,30])

In [10]:
na

array([10, 20, 30])

In [11]:
type(na)

numpy.ndarray

In [14]:
chs = np.array( list("Python"))

In [15]:
chs

array(['P', 'y', 't', 'h', 'o', 'n'], dtype='<U1')

## Method to create array

In [20]:
zeros = np.zeros(10)

In [21]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
ones = np.ones(10)

In [25]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
d2 = np.full( (3,3), 10)

In [24]:
d2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [39]:
d2.shape

(3, 3)

In [31]:
ea = np.empty(5)

In [32]:
ea

array([8.48798316e-314, 3.39519327e-313, 7.63918485e-313, 1.35807731e-312,
       2.12199579e-312])

In [36]:
a = np.arange(1,11, dtype=np.int16)

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
a.dtype

dtype('int16')

In [38]:
a.shape

(10,)

In [40]:
a.size

10

In [41]:
d2.size

9

In [42]:
d2.dtype

dtype('int32')

In [43]:
d2.ndim

2

In [44]:
a.ndim

1

## Random nums generation

In [46]:
ra = np.random.randint(10,20,10)

In [47]:
ra

array([10, 11, 19, 18, 17, 13, 10, 10, 16, 16])

In [55]:
aa,sv =  np.linspace(1,10,20, retstep=True)

In [56]:
aa

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [57]:
sv

0.47368421052631576

## Indexing

In [59]:
a = np.arange(1,11)

In [60]:
a[1]

2

In [61]:
a[5:]

array([ 6,  7,  8,  9, 10])

In [62]:
a[-1]

10

In [63]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [64]:
a[-5:8]

array([6, 7, 8])

In [66]:
td = np.arange(1,10).reshape((3,3))

In [67]:
td

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
td[1,1]

5

In [70]:
td[1,-1]

6

In [74]:
td[1]   

array([4, 5, 6])

In [75]:
td[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
td[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [78]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:

a.sum()

55

In [25]:
a = np.random.randint(10,20,10)
ai =  [2,4,7]
print(a)
a[ai]

[15 10 19 14 13 14 12 19 11 14]


array([19, 13, 19])

In [28]:
l = [10,20,30]
l * 2

[10, 20, 30, 10, 20, 30]

In [32]:
b = a + 10
type(b)

numpy.ndarray

In [31]:
b

array([25, 20, 29, 24, 23, 24, 22, 29, 21, 24])

In [34]:
print(a)
print(a % 2 == 0)

[15 10 19 14 13 14 12 19 11 14]
[False  True False  True False  True  True False False  True]


In [35]:
a1 = np.array([1,2,3,4,5])

In [38]:
a1[ [True,False,True,True,False]]

array([1, 3, 4])

In [46]:
ba = a > 15
print(ba)
print(type(ba))
ln = a[ba]
print(ln)

[False False  True False False False False  True False False]
<class 'numpy.ndarray'>
[19 19]


In [41]:
type(en)

numpy.ndarray

## View vs. Copy

In [47]:
a

array([15, 10, 19, 14, 13, 14, 12, 19, 11, 14])

In [48]:
a1 = a[0:5]

In [49]:
a1

array([15, 10, 19, 14, 13])

In [50]:
a1[0] = 100

In [51]:
a

array([100,  10,  19,  14,  13,  14,  12,  19,  11,  14])

In [52]:
a[0:3] = 0

In [54]:
a1[:]= 0

In [55]:
a

array([ 0,  0,  0,  0,  0, 14, 12, 19, 11, 14])

In [56]:
b = a.view()
b = a[:]

In [58]:
a is b 

False

In [59]:
c = a.copy()

In [60]:
c[0] = 100

In [61]:
a

array([ 0,  0,  0,  0,  0, 14, 12, 19, 11, 14])

In [62]:
c

array([100,   0,   0,   0,   0,  14,  12,  19,  11,  14])

## Array Operations

In [67]:
a = np.arange(5)
b = np.arange(5)

In [68]:
a + b

array([0, 2, 4, 6, 8])

In [75]:
da =  np.arange(10).reshape(-1,5)

In [76]:
da

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
a1 = np.arange(10)

In [78]:
a2 = a1.reshape(2,-1)

In [79]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
a1[0] = 100

In [83]:
a2.reshape(5,-1)

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [84]:
a2

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [85]:
a2.resize(5,2)    # inplace resize 

In [87]:
a2.shape

(5, 2)

In [88]:
a2.shape = (1,10)

In [89]:
a2

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [90]:
a2.shape

(1, 10)

In [91]:
a.sum()

10

In [92]:
a.mean()

2.0

In [93]:
a.var()

2.0

In [94]:
a.std()

1.4142135623730951