In [37]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1,2,3])

In [3]:
s

0    1
1    2
2    3
dtype: int64

In [11]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [21]:
marks = pd.Series([88,47,76], index=[101,102,103])

In [5]:
marks

101    88
102    47
103    76
dtype: int64

In [15]:
names = pd.Series(['Bill','Larry','Mark'], index=list('123'))

In [16]:
names.index

Index(['1', '2', '3'], dtype='object')

In [20]:
names[1]

'Larry'

In [8]:
h = pd.Series([150.5,160.8,128.5])

In [9]:
h

0    150.5
1    160.8
2    128.5
dtype: float64

In [10]:
h[0]

150.5

In [12]:
marks[101]

88

In [13]:
marks.index

Int64Index([101, 102, 103], dtype='int64')

In [14]:
marks.values

array([88, 47, 76], dtype=int64)

In [22]:
for n in marks.items():
    print(n)

(101, 88)
(102, 47)
(103, 76)


In [24]:
marks.is_unique

True

In [25]:
marks.shape

(3,)

In [26]:
marks.size

3

In [27]:
marks.values

array([88, 47, 76], dtype=int64)

In [28]:
marks[101] = 90

In [29]:
marks.values

array([90, 47, 76], dtype=int64)

In [32]:
det = marks.agg(['max','min'])

In [33]:
type(det)

pandas.core.series.Series

In [34]:
det

max    90
min    47
dtype: int64

In [35]:
det['max'] - det['min']

43

In [38]:
marks.apply()

101    90
102    47
103    76
dtype: int64

In [39]:
def make_pass(n):
    if n < 50:
        return 50
    else:
        return n

In [40]:
marks.apply(make_pass)

101    90
102    50
103    76
dtype: int64

In [41]:
marks

101    90
102    47
103    76
dtype: int64

In [42]:
marks.apply( lambda n : 50 if n < 50 else n)

101    90
102    50
103    76
dtype: int64

In [43]:
marks.apply( lambda n : f"{n:03d}")

101    090
102    047
103    076
dtype: object

In [44]:
marks.describe()

count     3.000000
mean     71.000000
std      21.931712
min      47.000000
25%      61.500000
50%      76.000000
75%      83.000000
max      90.000000
dtype: float64

In [45]:
marks.var()

481.0

In [46]:
marks.cumsum()

101     90
102    137
103    213
dtype: int64

In [47]:
marks.sort_values()

102    47
103    76
101    90
dtype: int64

In [48]:
marks.sort_index()

101    90
102    47
103    76
dtype: int64

In [49]:
s = pd.Series([1,2,3], index=[1,1,2])

In [50]:
s

1    1
1    2
2    3
dtype: int64

In [51]:
s[1]

1    1
1    2
dtype: int64

In [74]:
s.to_dict()

{1: 2, 2: 3}

In [57]:
marks.rank()

101    3.0
102    1.0
103    2.0
dtype: float64

In [59]:
marks[104]=90

In [60]:
marks

101    90
102    47
103    76
104    90
dtype: int64

In [67]:
marks.sort_values(ascending=False).rank()

104    3.5
101    3.5
103    2.0
102    1.0
dtype: float64

In [64]:
marks.sort_values().pct_change()

102         NaN
103    0.617021
101    0.184211
104    0.000000
dtype: float64

In [65]:
marks.sort_values()

102    47
103    76
101    90
104    90
dtype: int64

3

In [69]:
marks >= 50

101     True
102    False
103     True
104     True
dtype: bool

In [72]:
marks.tolist()

[90, 47, 76, 90]

In [73]:
marks.to_dict()

{101: 90, 102: 47, 103: 76, 104: 90}

In [75]:
marks.to_json()

'{"101":90,"102":47,"103":76,"104":90}'

In [76]:
marks.to_csv("newmarks.csv")

In [77]:
marks.value_counts()

90    2
47    1
76    1
dtype: int64