In [2]:
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [3]:
age_train = np.array([21,22,20,24,23]).reshape(-1,1)
income_train = [3,4,4,6,5]

age_test = np.array([22,24]).reshape(-1,1)
income_test = [4,5]

In [4]:
age_train

array([[21],
       [22],
       [20],
       [24],
       [23]])

In [5]:
model = LinearRegression()

In [20]:
model.fit(age_train, income_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
model.intercept_

-8.799999999999997

In [22]:
model.coef_

array([0.6])

In [23]:
income_pred = model.predict(age_test)

In [24]:
income_pred

array([4.4, 5.6])

In [25]:
income_test

[4, 5]

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [13]:
mae = mean_absolute_error(income_test, income_pred)

In [14]:
mae

0.5

In [15]:
mse = mean_squared_error(income_test, income_pred)

In [16]:
mse

0.25999999999999995

In [26]:
r2score = r2_score(income_test, income_pred)

In [27]:
r2score

-0.039999999999999813